# Generated by Django 3.0.8 on 2020-07-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='One ingredient per line', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.TextField(blank=True, default='', verbose_name='Link(s)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(blank=True, verbose_name='Preparation'),
        ),
    ]
