# Generated by Django 3.0.8 on 2020-07-17 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 0, 52, 13, 238404, tzinfo=utc), verbose_name='date published'),
        ),
    ]
