# Generated by Django 3.0.8 on 2020-07-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20200719_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
